#!/bin/sh
##SBATCH --parition=debug
#SBATCH --time=00:30:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=8
##SBATCH --mem=24000
#SBATCH --job-name="jacobi_test"
#SBATCH --output=test.out
#SBATCH --mail-user=naveenud@buffalo.edu
#SBATCH --mail-type=ALL

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST="$SLURM_JOB_NODELIST
echo "SLURM_NNODES="$SLURM_NNODES
echo "SLURM_TMPDIR="$SLURMTMPDIR
echo "Working Directory="$SLURM_SUBMIT_DIR

module load intel/14.0
module load intel-mpi/4.1.3
module list
ulimit -s unlimited 
#

#export I_MPI_DEBUG=4
#NPROCS=`srun --nodes=${SLURM_NNODES} bash -c 'hostname' | wc -l`
#echo "NPROCS="$NPROCS
echo "Launch mpi_jacobi with srun"
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun ./mpi_jacobi

#
echo "All Done!"
